# Generated by Django 4.2.11 on 2026-03-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pew_be', '0005_product_best_use_product_capacity_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mount_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
    ]
